GET http://localhost:8080/bookstore-microprofile/resources/books

###
POST http://localhost:8080/bookstore-microprofile/resources/books
Authorization: Bearer eyJraWQiOiJcL3ByaXZhdGVLZXkucGVtIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkdWtlIiwidXBuIjoiZHVrZSIsImF1dGhfdGltZSI6MTU2NzAwMTI2MCwiaXNzIjoiYWlyaGFja3MiLCJncm91cHMiOlsiY2hpZWYiLCJoYWNrZXIiXSwiZXhwIjoxNTY3MDAyMjYwLCJpYXQiOjE1NjcwMDEyNjAsImp0aSI6IjQyIn0.aSWWo4QPPjjkUg43sg4A6cVz_LTYVS3q5IryrpZSmGBs1dX9Bn6FfyvBYZF0YlI0jJlzsW2VeThWXWo8BKP-M688bda_vp0ZP17jZmpQAjCrr1ZJ6zSlBf4IziGPO_z7KK8V41If08wyonJ6973pAVUPNqjTf2yRqNH5fooL0a5wjaYOtTTE4n-z7wIa9XRL64pLv176fllUojhGmJzxds_wcJ0dRR292YB3vIR6-l3okMKp-SNKSVn0Cta3XMo_tTnIhXcLygGyi3AWG_iOtpuT0WuOvnXDP9-ZBGvY1CR3iwHLfSawmhX59slsP6kIo0nL8tzMoNARF2-JfkJFvg
Content-Type: application/json

{
  "title": "Some new Book",
  "author": "Great Author"
}
###
