GET http://localhost:8080/bookstore-microprofile/resources/books

###
POST http://localhost:8080/bookstore-microprofile/resources/books
Authorization: Bearer eyJraWQiOiJcL3ByaXZhdGVLZXkucGVtIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkdWtlIiwidXBuIjoiZHVrZSIsImF1dGhfdGltZSI6MTU2Njk4MzUwNCwiaXNzIjoiYWlyaGFja3MiLCJncm91cHMiOlsiY2hpZWYiLCJoYWNrZXIiXSwiZXhwIjoxNTY2OTg0NTA0LCJpYXQiOjE1NjY5ODM1MDQsImp0aSI6IjQyIn0.J7ri8yx-jcJozulbKllb0pRwK4yeqpxH7FJEuRA_kvF2HG127chhJ4U8PvuaLOJJLN5RWdSSuZcqF_4utYvhRIUtIBwtlZWJQ74gprs8fAG-Rf_WXvERBh0516dGEzz6JcsE78wsRYL8PVZwa5PgG74XJU5iXbDgiy72MF-Y6THZDZzwV6IQwvMhBeHlqvjcM1GNLmF6b5mnDaF83lSnqMxkwETJg5A9BEusVSVJcPOdd1J4Ab4xUY38-P9gwkOKCAdL2F1_HAyt5wharH-cvfwE3tmS6HcVxnTlL8k7qD3mnJRuf3pu8v_Wxd6-9vOG5pEmwaHMzk_08pDOk9l77w
Content-Type: application/json

{
  "title": "Some new Book",
  "author": "Great Author"
}
###
