GET http://localhost:8080/bookstore-microprofile/resources/ping
Authorization: Bearer eyJraWQiOiJqd3Qua2V5IiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJkdWtlIiwidXBuIjoiZHVrZSIsImF1dGhfdGltZSI6MTU2NjkwNzY3MywiaXNzIjoiYWlyaGFja3MiLCJncm91cHMiOlsiY2hpZWYiLCJoYWNrZXIiXSwiZXhwIjoxNTY2OTA4NjczLCJpYXQiOjE1NjY5MDc2NzMsImp0aSI6IjQyIn0.Uk3kCNmJPiu-sOQeBBwBZi9CKbXDYI6pH9UpS0Wg7lx9ejsjJDIPNb3A8-guYZp4sBAPfnaN2dfw96kfQAp5xTUmWsD9e0M30sK-F0g89_9iOCbzgx359XdfDWFWfm_oS0nCjaFZItPktbhahWKnlgQ6dJifpm-ySObKCt0IhWjUoWUt4ap6S16T8ucEPDQ3v3wcj3DuOCAcXXlnK3B6_LyCG32zYtsJGpr4VQSD2rhIu-Cy7Ny97OxFzA57e2Vh6DoMzbosub9HxEyxvStvq5bHy4d48NrcJPIJLZEXxMyW6GVjqWzt3TmcTRrpAaIQyDujz6YikOf2EFjh-lbfJQ

###
